import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@styles/Index.module.css'
import Layouts from '@comp/layouts.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>My Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Layouts></Layouts>
      </main>
    </>
  )
}
